### ISSUE TITLE
where is SmileIdentityCore.php file?

### ISSUE THREAD

**Issue by discovermasroor** [smileidentity/smile-identity-core-php#4]
where is SmileIdentityCore.php file?

**Comment by mldangelo** [comment]
Hi @discovermasroor, you can find the file [here](https://github.com/smileidentity/smile-identity-core-php/blob/main/lib/SmileIdentityCore.php). You can download published releases of this package from [here](https://packagist.org/packages/smile-identity/smile-identity-core). Please feel free to reach out or re-open the issue if you encounter any problems.
